FROM python:3.12-slim AS builder
WORKDIR /app
COPY pyproject.toml ./
RUN pip install --no-cache-dir ".[dev]"
COPY . .

FROM python:3.12-slim AS runner
WORKDIR /app
COPY --from=builder /app /app
CMD ["python", "src/main.py"]
