import { existsSync, readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import Handlebars from 'handlebars';
import { findTemplatesDir, buildContext } from '../quick/scaffold.js';
import { getDevCommand, getTestCommand } from '../quick/dev-command.js';
import { getStack } from '../quick/stacks.js';
import { detectStack } from '../../utils/detect-stack.js';
import { replaceRegion, hasRegion } from '../../utils/regions.js';
import { scanStructure } from './scan.js';
import { logger } from '../../logger.js';

export interface SyncOptions {
  targetDir: string;
  projectName: string;
  description: string;
  stack?: string;
  dryRun?: boolean;
}

export interface SyncResult {
  /** 'updated' = managed region changed; 'unchanged' = already in sync; 'created' = file made. */
  status: 'updated' | 'unchanged' | 'created' | 'skipped';
  stack: string;
  file: string;
}

/** Build the body that lives between the tk:managed markers. */
export function buildManagedBody(stack: string, structure: string): string {
  const label = getStack(stack)?.label ?? stack;
  const dev = getDevCommand(stack);
  const test = getTestCommand(stack);

  const meta = [`**Stack:** ${label}`];
  if (dev) meta.push(`**Dev:** \`${dev}\``);
  if (test) meta.push(`**Test:** \`${test}\``);

  return [
    '',
    '<!-- Regenerated by `tk sync`. Do not edit between these markers — changes are overwritten. -->',
    '',
    meta.join(' · '),
    '',
    '## Project Structure',
    '',
    '```',
    structure,
    '```',
    '',
  ].join('\n');
}

/** Render a fresh CLAUDE.md from the stack (or shared) template. */
function renderBaseClaude(templatesDir: string, stack: string, ctx: ReturnType<typeof buildContext>): string {
  const stackTpl = join(templatesDir, stack, 'CLAUDE.md.hbs');
  const sharedTpl = join(templatesDir, 'shared', 'CLAUDE.md.hbs');
  const tplPath = existsSync(stackTpl) ? stackTpl : sharedTpl;
  return Handlebars.compile(readFileSync(tplPath, 'utf-8'))(ctx);
}

/**
 * Regenerate the tk:managed region of CLAUDE.md from the project's real structure.
 * Never touches the tk:user region. Creates CLAUDE.md from the template if absent.
 */
export async function syncProject(opts: SyncOptions): Promise<SyncResult> {
  const { targetDir, projectName, description, dryRun } = opts;

  if (!existsSync(targetDir)) {
    throw new Error(`Directory "${targetDir}" does not exist.`);
  }

  const stack = opts.stack || detectStack(targetDir);
  const claudePath = join(targetDir, 'CLAUDE.md');
  const structure = scanStructure(targetDir);
  const managedBody = buildManagedBody(stack, structure);

  const templatesDir = findTemplatesDir();
  const ctx = buildContext({
    projectName, description, stack, targetDir,
    includeAi: true, initGit: false, installDeps: false,
  });

  // No CLAUDE.md yet → render the base template, then inject the live structure.
  if (!existsSync(claudePath)) {
    const base = renderBaseClaude(templatesDir, stack, ctx);
    const synced = replaceRegion(base, 'managed', managedBody);
    if (dryRun) {
      logger.info(`[dry-run] Would create CLAUDE.md (stack: ${stack}) with live project structure`);
      return { status: 'skipped', stack, file: claudePath };
    }
    writeFileSync(claudePath, synced, 'utf-8');
    logger.success(`Created CLAUDE.md and synced structure (stack: ${stack})`);
    return { status: 'created', stack, file: claudePath };
  }

  const existing = readFileSync(claudePath, 'utf-8');

  if (!hasRegion(existing, 'managed')) {
    logger.warn('CLAUDE.md has no tk:managed region — leaving it untouched. Run `tk update` to refresh the template, or add the markers manually.');
    return { status: 'skipped', stack, file: claudePath };
  }

  const synced = replaceRegion(existing, 'managed', managedBody);

  if (synced === existing) {
    if (!dryRun) logger.info('CLAUDE.md already in sync with the project structure.');
    return { status: 'unchanged', stack, file: claudePath };
  }

  if (dryRun) {
    logger.info(`[dry-run] Would update CLAUDE.md managed region (stack: ${stack})`);
    return { status: 'skipped', stack, file: claudePath };
  }

  writeFileSync(claudePath, synced, 'utf-8');
  logger.success(`Synced CLAUDE.md structure (stack: ${stack})`);
  return { status: 'updated', stack, file: claudePath };
}
