/**
 * Managed / user region handling for tk-maintained context files (e.g. CLAUDE.md).
 *
 * Two region kinds, each delimited by HTML comment markers:
 *   - tk:managed  — regenerated by `tk sync` from the project's real structure.
 *   - tk:user     — owned by the user; tk never overwrites its body.
 *
 * The markers are HTML comments so they render invisibly in Markdown.
 */

export const MANAGED_START = '<!-- tk:managed:start -->';
export const MANAGED_END = '<!-- tk:managed:end -->';
export const USER_START = '<!-- tk:user:start -->';
export const USER_END = '<!-- tk:user:end -->';

function regionRegex(startMarker: string, endMarker: string): RegExp {
  // Capture group 1 = body between the start marker and the end marker.
  const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  return new RegExp(`${esc(startMarker)}([\\s\\S]*?)${esc(endMarker)}`);
}

/** Return the body between a region's markers, or null if the region is absent. */
export function extractRegion(content: string, kind: 'managed' | 'user'): string | null {
  const [start, end] = kind === 'managed' ? [MANAGED_START, MANAGED_END] : [USER_START, USER_END];
  const match = content.match(regionRegex(start, end));
  return match ? match[1] : null;
}

/** Replace a region's body in `content`. Returns content unchanged if the region is absent. */
export function replaceRegion(content: string, kind: 'managed' | 'user', newBody: string): string {
  const [start, end] = kind === 'managed' ? [MANAGED_START, MANAGED_END] : [USER_START, USER_END];
  const re = regionRegex(start, end);
  if (!re.test(content)) return content;
  return content.replace(re, `${start}${newBody}${end}`);
}

export function hasRegion(content: string, kind: 'managed' | 'user'): boolean {
  const [start, end] = kind === 'managed' ? [MANAGED_START, MANAGED_END] : [USER_START, USER_END];
  return content.includes(start) && content.includes(end);
}

/**
 * Merge a freshly-rendered template with an existing on-disk file, preserving the
 * user's tk:user region. If either side lacks a user region, the fresh render wins.
 */
export function mergePreservingUser(fresh: string, existing: string): string {
  const existingUserBody = extractRegion(existing, 'user');
  if (existingUserBody === null) return fresh;
  return replaceRegion(fresh, 'user', existingUserBody);
}
